name: Alert
main: alert.Alert
version: 1
commands:
    setworld:
        description: Set the world for the chest counter.
        usage: /setworld <world>
        permission: alert.admin
        permission-message: LOL NOPE!!!
    showworld:
        description: Display the world that is set.
        usage: /showworld
        permission: alert.admin
        permission-message: LOL NOPE!!!
    countchests:
        description: Shows the type and amount of chests on the world.
        usage: /countchests
        permission: alert.admin
        permission-message: LOL NOPE!!!
    reset:
        description: Reset the chest count.
        usage: /reset
        permission: alert.admin
        permission-message: LOL NOPE!!!